app:
  name: template
  secret: 123456
http:
  host: 127.0.0.1
  port: 8080
mysql:
  host: 127.0.0.1
  port: 3306
  database: campus_second-hand
  username: root
  password: 123456
redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  password: